1 int _putchar(char c);
2 char *_memset(char *s, char b, unsigned int n);
3 char *_memcpy(char *dest, char *src, unsigned int n);
4 char *_strchr(char *s, char *accept);
5 unsigned int _strspn(char *s, char c);
6 char *_strpbrk(char *s, char *accept);
7 char *_strstr(char *haystack, char *needle);
8 void print_chessboard(char (*a)[8]);
9 void print_diagsums(int *a, int size);
10 void set_string(char **s, char *to);
